# Logging
logging.level:
    'root': warn
    'com.pwmcintyre': debug
    'org.springframework.cache': DEBUG
    'org.apache.kafka': warn

# Spring Boot
spring.main.web-application-type: NONE

# Kafka
#kafka.persons.topic.name: persons
#kafka.movies.topic.name: movies

kafka:
    bootstrap-servers: localhost:9092
    persons:
        consumer.group-id: ${random.uuid}
        topic.name: persons
    movies:
        consumer.group-id: ${random.uuid}
        topic.name: movies

# Kafka Producer
spring.kafka.producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: com.pwmcintyre.kafka.serde.base64.Base64Serializer
    properties:
        '[base64.inner.serializer]': org.springframework.kafka.support.serializer.JsonSerializer
        '[spring.json.use.type.headers]': true

# Kafka Consumer
spring.kafka.consumer:
    group-id: ${random.uuid}
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: com.pwmcintyre.kafka.serde.base64.Base64Deserializer
    properties:
        '[base64.inner.deserializer]': org.springframework.kafka.support.serializer.JsonDeserializer
#        '[spring.json.value.default.type]': person=com.pwmcintyre.kafka.model.Person,movie=com.pwmcintyre.kafka.model.Movie
        '[spring.json.trusted.packages]': com.pwmcintyre.*
